Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,43 +1,43 @@
-name: Build and Test
+# name: Build and Test
 
-on:
-  push:
-    paths:
-      - 'T-SQL/**'
+# on:
+#   push:
+#     paths:
+#       - 'T-SQL/**'
   
-jobs:
-  build:
-    runs-on: ubuntu-latest
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
 
-      - name: Install sqlcmd
-        run: |
-          sudo mkdir -p /etc/apt/keyrings
-          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /etc/apt/keyrings/microsoft-prod.gpg
-          echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/20.04/prod focal main" | sudo tee /etc/apt/sources.list.d/msprod.list
-          sudo rm /etc/apt/sources.list.d/microsoft-prod.list || true
-          sudo apt-get update
-          sudo apt-get install -y apt-transport-https
-          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
-          echo 'PATH=/opt/mssql-tools/bin:$PATH' >> $GITHUB_ENV
+#       - name: Install sqlcmd
+#         run: |
+#           sudo mkdir -p /etc/apt/keyrings
+#           curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /etc/apt/keyrings/microsoft-prod.gpg
+#           echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/20.04/prod focal main" | sudo tee /etc/apt/sources.list.d/msprod.list
+#           sudo rm /etc/apt/sources.list.d/microsoft-prod.list || true
+#           sudo apt-get update
+#           sudo apt-get install -y apt-transport-https
+#           sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
+#           echo 'PATH=/opt/mssql-tools/bin:$PATH' >> $GITHUB_ENV
 
-      - name: Verify sqlcmd installation
-        shell: bash
-        run: |
-          source $GITHUB_ENV
-          echo $PATH
-          if ! command -v sqlcmd &> /dev/null
-          then
-              echo "sqlcmd could not be found"
-              exit 1
-          fi
-          sqlcmd -? || { echo "sqlcmd help command failed"; exit 1; }
+#       - name: Verify sqlcmd installation
+#         shell: bash
+#         run: |
+#           source $GITHUB_ENV
+#           echo $PATH
+#           if ! command -v sqlcmd &> /dev/null
+#           then
+#               echo "sqlcmd could not be found"
+#               exit 1
+#           fi
+#           sqlcmd -? || { echo "sqlcmd help command failed"; exit 1; }
 
-      - name: Run sqlcmd command
-        shell: bash
-        run: |
-          source $GITHUB_ENV
-          sqlcmd -S ${{ secrets.DB_HOSTNAME }},1433 -U ${{ secrets.DB_USERNAME }} -P ${{ secrets.DB_PASSWORD }} -Q "SELECT name"
+#       - name: Run sqlcmd command
+#         shell: bash
+#         run: |
+#           source $GITHUB_ENV
+#           sqlcmd -S ${{ secrets.DB_HOSTNAME }},1433 -U ${{ secrets.DB_USERNAME }} -P ${{ secrets.DB_PASSWORD }} -Q "SELECT name"
